# NXP HTG940 profile: USB FMC D, I3C FMC C; no external processor JTAG.
# Verify connector and VADJ settings match this profile before programming.
# Clock/reset/LED pins match the tested HTG940 smoke design.
set_property IOSTANDARD LVDS [get_ports ref_clock_156p25mhz_clk_p]
set_property PACKAGE_PIN AW28 [get_ports ref_clock_156p25mhz_clk_p]
set_property PACKAGE_PIN AY28 [get_ports ref_clock_156p25mhz_clk_n]
set_property IOSTANDARD LVDS [get_ports ref_clock_156p25mhz_clk_n]
set_property PACKAGE_PIN AJ34 [get_ports resetn_i]
set_property IOSTANDARD LVCMOS12 [get_ports resetn_i]
set_property PACKAGE_PIN AK32 [get_ports usb_phy_resetn_i]
set_property IOSTANDARD LVCMOS12 [get_ports usb_phy_resetn_i]
set_property PACKAGE_PIN BB22 [get_ports usb_phy_resetn_o]
set_property IOSTANDARD LVCMOS18 [get_ports usb_phy_resetn_o]
set_property PACKAGE_PIN AP28 [get_ports {GPIO_o[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_o[0]}]
set_property PACKAGE_PIN AN28 [get_ports {GPIO_o[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_o[1]}]
set_property PACKAGE_PIN AP26 [get_ports {GPIO_o[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_o[2]}]
set_property PACKAGE_PIN AW16 [get_ports cptra_ss_usb_ulpi_clk_i]
set_property IOSTANDARD LVCMOS18 [get_ports cptra_ss_usb_ulpi_clk_i]
set_property PACKAGE_PIN AL15 [get_ports {cptra_ss_usb_ulpi_data_io[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cptra_ss_usb_ulpi_data_io[0]}]
set_property PACKAGE_PIN AM15 [get_ports {cptra_ss_usb_ulpi_data_io[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cptra_ss_usb_ulpi_data_io[1]}]
set_property PACKAGE_PIN AP15 [get_ports {cptra_ss_usb_ulpi_data_io[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cptra_ss_usb_ulpi_data_io[2]}]
set_property PACKAGE_PIN AM14 [get_ports {cptra_ss_usb_ulpi_data_io[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cptra_ss_usb_ulpi_data_io[3]}]
set_property PACKAGE_PIN AN14 [get_ports {cptra_ss_usb_ulpi_data_io[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cptra_ss_usb_ulpi_data_io[4]}]
set_property PACKAGE_PIN AN13 [get_ports {cptra_ss_usb_ulpi_data_io[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cptra_ss_usb_ulpi_data_io[5]}]
set_property PACKAGE_PIN AT15 [get_ports {cptra_ss_usb_ulpi_data_io[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cptra_ss_usb_ulpi_data_io[6]}]
set_property PACKAGE_PIN AU15 [get_ports {cptra_ss_usb_ulpi_data_io[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cptra_ss_usb_ulpi_data_io[7]}]
set_property PACKAGE_PIN AW15 [get_ports cptra_ss_usb_ulpi_dir_i]
set_property IOSTANDARD LVCMOS18 [get_ports cptra_ss_usb_ulpi_dir_i]
set_property PACKAGE_PIN AL14 [get_ports cptra_ss_usb_ulpi_stp_o]
set_property IOSTANDARD LVCMOS18 [get_ports cptra_ss_usb_ulpi_stp_o]
set_property PACKAGE_PIN AP14 [get_ports cptra_ss_usb_ulpi_nxt_i]
set_property IOSTANDARD LVCMOS18 [get_ports cptra_ss_usb_ulpi_nxt_i]
set_property PACKAGE_PIN AN22 [get_ports cptra_ss_i3c_scl_io]
set_property IOSTANDARD LVCMOS18 [get_ports cptra_ss_i3c_scl_io]
set_property PACKAGE_PIN AN21 [get_ports cptra_ss_i3c_sda_io]
set_property IOSTANDARD LVCMOS18 [get_ports cptra_ss_i3c_sda_io]

create_clock -period 6.400 -name ref_clock_156p25mhz [get_ports ref_clock_156p25mhz_clk_p]
create_clock -period 16.667 -name usb_clk [get_ports cptra_ss_usb_ulpi_clk_i]

# ULPI timing budget supplied by NXP; board timing closure still needs validation.
set_input_delay -clock usb_clk -max 3.650 [get_ports {{cptra_ss_usb_ulpi_data_io[*]} cptra_ss_usb_ulpi_dir_i cptra_ss_usb_ulpi_nxt_i}]
set_input_delay -clock usb_clk -min 1.000 [get_ports {{cptra_ss_usb_ulpi_data_io[*]} cptra_ss_usb_ulpi_dir_i cptra_ss_usb_ulpi_nxt_i}]
set_output_delay -clock usb_clk -max 5.150 [get_ports {{cptra_ss_usb_ulpi_data_io[*]} cptra_ss_usb_ulpi_stp_o}]
set_output_delay -clock usb_clk -min 0.000 [get_ports {{cptra_ss_usb_ulpi_data_io[*]} cptra_ss_usb_ulpi_stp_o}]


# No blanket asynchronous clock groups or DRC downgrades are imported.
# I3C is externally asynchronous and sampled through existing synchronizers.


# HTG940_ENTROPY_CONTROL_V1
# CP2103 VIO is powered by VADJ_FMC_A. This profile requires 1.8 V there.
# Net UART_TXD is the CP2103 output, hence FPGA input R15.
set_property PACKAGE_PIN R15 [get_ports host_uart_rx_i]
set_property IOSTANDARD LVCMOS18 [get_ports host_uart_rx_i]
set_property PULLTYPE PULLUP [get_ports host_uart_rx_i]
set_property PACKAGE_PIN P15 [get_ports host_uart_tx_o]
set_property IOSTANDARD LVCMOS18 [get_ports host_uart_tx_o]

# HTG940_NO_FMC_JTAG_V1: J3 configuration JTAG uses dedicated FPGA pins.

set_property MARK_DEBUG true [get_nets {u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/usb_ulpi_txdata[0]}]
set_property MARK_DEBUG true [get_nets {u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/usb_ulpi_txdata[1]}]
set_property MARK_DEBUG true [get_nets {u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/usb_ulpi_txdata[2]}]
set_property MARK_DEBUG true [get_nets {u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/usb_ulpi_txdata[3]}]
set_property MARK_DEBUG true [get_nets {u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/usb_ulpi_txdata[4]}]
set_property MARK_DEBUG true [get_nets {u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/usb_ulpi_txdata[5]}]
set_property MARK_DEBUG true [get_nets {u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/usb_ulpi_txdata[6]}]
set_property MARK_DEBUG true [get_nets {u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/usb_ulpi_txdata[7]}]
set_property MARK_DEBUG true [get_nets u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/usb_ulpi_txenable]
set_property MARK_DEBUG true [get_nets {u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/caliptra_ss_top_0/cptra_ss_usb_ulpi_rxdata_i[0]}]
set_property MARK_DEBUG true [get_nets {u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/caliptra_ss_top_0/cptra_ss_usb_ulpi_rxdata_i[1]}]
set_property MARK_DEBUG true [get_nets {u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/caliptra_ss_top_0/cptra_ss_usb_ulpi_rxdata_i[2]}]
set_property MARK_DEBUG true [get_nets {u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/caliptra_ss_top_0/cptra_ss_usb_ulpi_rxdata_i[3]}]
set_property MARK_DEBUG true [get_nets {u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/caliptra_ss_top_0/cptra_ss_usb_ulpi_rxdata_i[4]}]
set_property MARK_DEBUG true [get_nets {u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/caliptra_ss_top_0/cptra_ss_usb_ulpi_rxdata_i[5]}]
set_property MARK_DEBUG true [get_nets {u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/caliptra_ss_top_0/cptra_ss_usb_ulpi_rxdata_i[6]}]
set_property MARK_DEBUG true [get_nets {u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/caliptra_ss_top_0/cptra_ss_usb_ulpi_rxdata_i[7]}]
set_property MARK_DEBUG true [get_nets cptra_ss_usb_ulpi_dir_i_IBUF]
set_property MARK_DEBUG true [get_nets cptra_ss_usb_ulpi_nxt_i_IBUF]
set_property MARK_DEBUG true [get_nets u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/caliptra_ss_top_0/usb_core_i/u_hub_compound/usb_pie_1/cptra_ss_usb_ulpi_stp_o]

create_debug_core ulpi_ila ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores ulpi_ila]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores ulpi_ila]
set_property C_ADV_TRIGGER false [get_debug_cores ulpi_ila]
set_property C_DATA_DEPTH 4096 [get_debug_cores ulpi_ila]
set_property C_EN_STRG_QUAL false [get_debug_cores ulpi_ila]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores ulpi_ila]
set_property C_TRIGIN_EN false [get_debug_cores ulpi_ila]
set_property C_TRIGOUT_EN false [get_debug_cores ulpi_ila]
set_property port_width 1 [get_debug_ports ulpi_ila/clk]
connect_debug_port ulpi_ila/clk [get_nets [list cptra_ss_usb_ulpi_clk_i_IBUF]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports ulpi_ila/probe0]
set_property port_width 8 [get_debug_ports ulpi_ila/probe0]
connect_debug_port ulpi_ila/probe0 [get_nets [list {u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/usb_ulpi_txdata[0]} {u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/usb_ulpi_txdata[1]} {u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/usb_ulpi_txdata[2]} {u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/usb_ulpi_txdata[3]} {u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/usb_ulpi_txdata[4]} {u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/usb_ulpi_txdata[5]} {u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/usb_ulpi_txdata[6]} {u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/usb_ulpi_txdata[7]}]]
create_debug_port ulpi_ila probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports ulpi_ila/probe1]
set_property port_width 1 [get_debug_ports ulpi_ila/probe1]
connect_debug_port ulpi_ila/probe1 [get_nets [list u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/usb_ulpi_txenable]]
create_debug_port ulpi_ila probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports ulpi_ila/probe2]
set_property port_width 8 [get_debug_ports ulpi_ila/probe2]
connect_debug_port ulpi_ila/probe2 [get_nets [list {u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/caliptra_ss_top_0/cptra_ss_usb_ulpi_rxdata_i[0]} {u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/caliptra_ss_top_0/cptra_ss_usb_ulpi_rxdata_i[1]} {u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/caliptra_ss_top_0/cptra_ss_usb_ulpi_rxdata_i[2]} {u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/caliptra_ss_top_0/cptra_ss_usb_ulpi_rxdata_i[3]} {u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/caliptra_ss_top_0/cptra_ss_usb_ulpi_rxdata_i[4]} {u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/caliptra_ss_top_0/cptra_ss_usb_ulpi_rxdata_i[5]} {u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/caliptra_ss_top_0/cptra_ss_usb_ulpi_rxdata_i[6]} {u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/caliptra_ss_top_0/cptra_ss_usb_ulpi_rxdata_i[7]}]]
create_debug_port ulpi_ila probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports ulpi_ila/probe3]
set_property port_width 1 [get_debug_ports ulpi_ila/probe3]
connect_debug_port ulpi_ila/probe3 [get_nets [list cptra_ss_usb_ulpi_dir_i_IBUF]]
create_debug_port ulpi_ila probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports ulpi_ila/probe4]
set_property port_width 1 [get_debug_ports ulpi_ila/probe4]
connect_debug_port ulpi_ila/probe4 [get_nets [list cptra_ss_usb_ulpi_nxt_i_IBUF]]
create_debug_port ulpi_ila probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports ulpi_ila/probe5]
set_property port_width 1 [get_debug_ports ulpi_ila/probe5]
connect_debug_port ulpi_ila/probe5 [get_nets [list u_system/caliptra_htg940_bd_i/caliptra_package_top_0/inst/cptra_wrapper/caliptra_ss_top_0/usb_core_i/u_hub_compound/usb_pie_1/cptra_ss_usb_ulpi_stp_o]]
set_property MARK_DEBUG true [get_nets cptra_ss_usb_ulpi_clk_i_IBUF]
create_debug_core ulpi_clock_ila ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores ulpi_clock_ila]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores ulpi_clock_ila]
set_property C_ADV_TRIGGER false [get_debug_cores ulpi_clock_ila]
set_property C_DATA_DEPTH 4096 [get_debug_cores ulpi_clock_ila]
set_property C_EN_STRG_QUAL false [get_debug_cores ulpi_clock_ila]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores ulpi_clock_ila]
set_property C_TRIGIN_EN false [get_debug_cores ulpi_clock_ila]
set_property C_TRIGOUT_EN false [get_debug_cores ulpi_clock_ila]
set_property port_width 1 [get_debug_ports ulpi_clock_ila/clk]
connect_debug_port ulpi_clock_ila/clk [get_nets [list u_system/caliptra_htg940_bd_i/htg940_clocks/inst/clk_in1_caliptra_htg940_bd_htg940_clocks_0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports ulpi_clock_ila/probe0]
set_property port_width 1 [get_debug_ports ulpi_clock_ila/probe0]
connect_debug_port ulpi_clock_ila/probe0 [get_nets [list cptra_ss_usb_ulpi_clk_i_IBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets cptra_ss_usb_ulpi_clk_i_IBUF]
